package jazzyframework.data.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a method as overriding an auto-generated CRUD operation.
 * 
 * <p>This annotation is purely for documentation and code clarity purposes.
 * It indicates that the method replaces the default implementation that would
 * be automatically generated by the @Crud annotation.
 * 
 * <p>Valid method names for override:
 * <ul>
 *   <li>findAll - overrides GET /endpoint</li>
 *   <li>findById - overrides GET /endpoint/{id}</li>
 *   <li>create - overrides POST /endpoint</li>
 *   <li>update - overrides PUT /endpoint/{id}</li>
 *   <li>delete - overrides DELETE /endpoint/{id}</li>
 * </ul>
 * 
 * <p>Example usage:
 * <pre>
 * {@code
 * @CrudOverride("Custom validation and password hiding")
 * public Response findById(Request request) {
 *     // Custom implementation
 * }
 * }
 * </pre>
 * 
 * @since 0.4.0
 * @author Caner Mastan
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface CrudOverride {
    
    /**
     * Description of what this override does differently from the default implementation.
     * 
     * @return description of the custom behavior
     */
    String value() default "Custom implementation";
    
    /**
     * The CRUD operation being overridden.
     * 
     * @return the operation type (findAll, findById, create, update, delete)
     */
    String operation() default "";
} 