# Generated by Jazzy. Do not edit manually.
import jazzy

import ./m00000000000000_create_widgets as m00000000000000_create_widgets

proc allMigrations*(): seq[Migration] =
  @[m00000000000000_create_widgets.jazzyMigration]
